name: Basic test 2
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies only
        uses: cypress-io/github-action@v6
        with:
          runTests: false
